### ISSUE TITLE
Freezes browser

### ISSUE THREAD

**Issue by thijsi123** [adamlui/chatgpt-auto-continue#10]
Hi, when the continue button appears it never auto continues and sometimes (~1/3 chance)freezes my whole web browser.

**Comment by adamlui** [comment]
hey @thijsi123 what browser and userscript manager do you use?

**Comment by thijsi123** [comment]
I'm currently using Edge with Tampermonkey 
I'll try using Chrome until I get a long prompt that needs to be continued.

**Comment by adamlui** [comment]
Hey @thijsi123 & @SapitoSucio I fixed in in v2023.11.3 https://greasyfork.chatgptautocontinue.com
