### ISSUE TITLE
[Question] Auto continue on inactive browser

### ISSUE THREAD

**Issue by thinhdnn** [adamlui/chatgpt-auto-continue#50]
I use:
Microsoft Edge
Version 126.0.2592.113 (Official build) (64-bit)

I use 2 browsers: Chrome and Edge. I run chatgpt and chatgpt-auto-continue on Edge. I run chatgpt and open Chrome to watch youtube. Back after 10 mins and see chatgpt-auto-continue click when I open Edge, if not it wait. So how to click without keep Edge open when I use 2 browers.

**Comment by adamlui** [comment]
Hey @thinhdnn thanks for the question and sorry for late reply, Chromium browsers sleep inactive tabs including when minimized so JavaScript cannot run, but there is a setting you can set to override it @ chrome://discards/ by finding the row for the ChatGPT tab, then click "toggle" in that row until the check mark changes to an "X"

![234262937-32f61fcf-8945-470a-bdad-5a8eca1d0e50](https://github.com/user-attachments/assets/09017d4d-87e1-4a48-837b-b6a8efbf6ef6)
