### ISSUE TITLE
有时候可以有时候不可以，怎么办

### ISSUE THREAD

**Issue by cheezmil** [adamlui/chatgpt-auto-continue#53]
![2024-07-29 03 59 25](https://github.com/user-attachments/assets/7297fc82-d148-4109-bafe-bf3afb54d280)
这个组件长这样子。

**Comment by adamlui** [comment]
嘿 @AlexanderDash，抱歉我才有时间阅读这篇文章，您的问题解决了吗？

**Comment by adamlui** [comment]
我不会读/写中文（我使用谷歌翻译），所以很抱歉给您带来理解上的麻烦，您能解释一下没有 Infinity 脚本的问题是什么吗？
