### ISSUE TITLE
Its not working anymore?

### ISSUE THREAD

**Issue by Mailootje** [adamlui/chatgpt-auto-continue#63]

**Comment by adamlui** [comment]
Thanks @Mailootje I'ma check out if the Continue button got updated by OpenAI

**Comment by adamlui** [comment]
Omg the limit is so high now, asking for 135 sentences still didn't trigger it

![image](https://github.com/user-attachments/assets/bc5f9935-1870-49c8-8a8b-b961df98edf3)

**Comment by Mailootje** [comment]
It's probably my own fault... I must have accidentally clicked the on/off button when I opened Tampermonkey.

**Comment by adamlui** [comment]
@Mailootje nah they updated the selector I'ma publish an update to chatpgt.js then bump the ver and let you know

**Comment by Mailootje** [comment]
Oh... I accidentally found a bug without even realizing it 😂

**Comment by adamlui** [comment]
Thakn you for your accident and if you click your userscript manager's icon in the browser toolbar > scroll to ChatGPT Auto-Continue > click "About ChatGPT Auto-Continue" > click "Check for updates" > click "Update" to 2024.9.15.1 it will work again

**Comment by Mailootje** [comment]
Thanks!

**Comment by adamlui** [comment]
No problem!

**Comment by Mailootje** [comment]
Hi, i didnt want to open a ticket again. But it seems like its not working again.
