### ISSUE TITLE
Script doesn't work anymore

### ISSUE THREAD

**Issue by Mailootje** [adamlui/chatgpt-auto-continue#64]
Hi,

It seems like the script doensn't work anymore.
Do they keep changing stuff?

![image](https://github.com/user-attachments/assets/f548bf4d-a1be-4764-bb03-8eea9b983297)

**Comment by adamlui** [comment]
hey @Mailootje I just tested and it still works for me, can you inspect the continue generating button next time it appears, then in elements, right-click on the <button> or <svg> and Copy Outer HTML and paste it here?

Also do you get an email notification or inbox (upper-right corner tray icon on GitHub) alert when I tag you?

**Comment by Mailootje** [comment]
Yes i get a email from you!
Currently relying directly from mail.


________________________________

**Comment by andrew-bierman** [comment]
I'm experiencing the same issue. I believe the problem is caused by the Dark Reader Chrome extension interfering with the styles of the 'Continue Generating' button.

Below is the outerHTML for the 'Continue Generating' button with Dark Reader enabled, in case it helps. Disabling Dark Reader and doing a full refresh resolved the issue—the script started working again! 😊

Hope this helps! Thank you for the script 

```html
<button class="btn relative btn-secondary whitespace-nowrap border-0 md:border" as="button">
  <div class="flex items-center justify-center">
    <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" class="-rotate-180 icon-xs">
      <path fill-rule="evenodd" clip-rule="evenodd" d="M4.47189 2.5C5.02418 2.5 5.47189 2.94772 5.47189 3.5V5.07196C7.17062 3.47759 9.45672 2.5 11.9719 2.5C17.2186 2.5 21.4719 6.75329 21.4719 12C21.4719 17.2467 17.2186 21.5 11.9719 21.5C7.10259 21.5 3.09017 17.8375 2.53689 13.1164C2.47261 12.5679 2.86517 12.0711 3.4137 12.0068C3.96223 11.9425 4.45901 12.3351 4.5233 12.8836C4.95988 16.6089 8.12898 19.5 11.9719 19.5C16.114 19.5 19.4719 16.1421 19.4719 12C19.4719 7.85786 16.114 4.5 11.9719 4.5C9.7515 4.5 7.75549 5.46469 6.38143 7H9C9.55228 7 10 7.44772 10 8C10 8.55228 9.55228 9 9 9H4.47189C3.93253 9 3.4929 8.57299 3.47262 8.03859C3.47172 8.01771 3.47147 7.99677 3.47189 7.9758V3.5C3.47189 2.94772 3.91961 2.5 4.47189 2.5Z" fill="currentColor" data-darkreader-inline-fill="" style="--darkreader-inline-fill: currentColor;"></path>
    </svg>Continue generating
  </div>
</button>
```

**Comment by adamlui** [comment]
@Mailootje @andrew-bierman ty for the insights, can you update by clicking userscript manager icon on toolbar > scroll to About ChatGPT Auto-Continue > Check for Updates > Update to 2024.92.5 and see if it works?

**Comment by Mailootje** [comment]
> @Mailootje @andrew-bierman ty for the insights, can you update by clicking userscript manager icon on toolbar > scroll to About ChatGPT Auto-Continue > Check for Updates > Update to 2024.92.5 and see if it works?

I will give it a try!

**Comment by adamlui** [comment]
@Mailootje can you cconfirm it works?

**Comment by Mailootje** [comment]
> @Mailootje can you cconfirm it works?

It works. Just tested it
