### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by a12930** [adamlui/chatgpt-auto-continue#9]
It no longer works since the update that moved the auto-generating button to the right... It probably doesn't recognize the button.

**Comment by adamlui** [comment]
@a12930 thanks for reporting this, I fixed it, can you update to 2023.8.2 @ https://greasyfork.org/en/scripts/466789-chatgpt-auto-continue?

**Comment by adamlui** [comment]
@a12930 can you confirm the latest version works for you?

**Comment by DiegoBoyer** [comment]
No, it does not work

**Comment by adamlui** [comment]
@DiegoBoyer actually I was just using it succesfully this morning, what is your browser and userscript manager?
